### ISSUE TITLE
Include reactions, stages, time and others in Storklight game

### ISSUE THREAD

**Issue by darewealth** [sanjeev309/storklight#1]
***Now my ideas are as follow***

I think It would be nice to have a landing page which will enable users to access some basic, but useful features. These features are **NEW GAME**, **HISTORY**, **SOUND CONTROL (on/off)**. For now, these aren't the main suggestions I want to suggest, but they are also needed.

![](https://i.imgur.com/W6AM0O4.png)

While I was playing the game, I noticed that when I used all the available lives finished the game sometimes continues without any indication like **GAME OVER**. I had to press the mobile back button to exit and start again. The game does not have a **PAUSE** button. I will be listing my suggestion below.

The aim of the game is simple. Player will control a flying bird to eat yellow balls flowing on the screen. There is also black balls that are meant to take away the lives of the bird.

***Suggestions***

It'd be great to have a reaction on touch whenever the bird touches a yellow ball is could signify a ***positive (Green)reaction***, and show ***a negative (red) reactions*** on the black balls.

![](https://i.imgur.com/jS6dRcI.png)

![](https://i.imgur.com/9aNAZap.png)

A **pause** is another useful feature which is really needed to make the game friendly.

**Time** feature is needed. There will be a time counter at the top of the application to show how long the player has been playing.

![](https://i.imgur.com/cLYfD1a.png)

**Stages** will be a good addition. Users will be able to choose stages based on what they can play. The stages could have different interface.

**Sound** is beneficial components for games like this. The game is still very new, but I think it can be improved and become an entertaining game. With
the addition of the features, I have suggested the game will be more fun to play. Those features are needed as soon as possible. I wish to have them on the application.

Thank you.

**Comment by sanjeev309** [comment]
Hi @darewealth , First of all thank you for taking out your time for the suggestions :)

The menu is highly required, I will be starting work on that soon. Will be getting the designs done in a day or two so might share here for completeness as well. 

For the stork's reaction, what according to you will be a good feedback? I was thinking along the lines of stork's glow vs fade. What do you expect the stork to behave like when hitting an orb or dark?

Time feature : Good suggestion! Never thought of this! Consider this included in the next release :+1: 

Pause: Will be pushed as a collective update with landing page, so yeah :)

Sound : This one might take more time than expected, Can you suggest a few sound effects/music scores that would match the ambience of the game? Orbs and Darks can also have their own sound effects. As always feel free to suggest , I will start looking out as well :)

Stages: What is your opinion on an infinite game where the game keeps on speeding up vs a game divided into stages? Which would be more entertaining and engaging according to you?

**Comment by sanjeev309** [comment]
Here are a few screenshots from the ongoing work:

Landing page will be a menu bar at the bottom where we have plenty of space. As of writing this, only play button has been made functional:

Screenshot:

![](https://imgur.com/zqSM22z.jpg)
--------------
Timer idea is great! The implementation is ready and done.

Screenshot:

![](https://imgur.com/6cO0eub.jpg)

Both of these updates will be pushed in the next beta release along with audio for bird and menu once i figure out the bug I have for loading audio on few android devices.

Stay tuned. Peace Out!

**Comment by darewealth** [comment]
Hey buddy, thanks. 

>According to this: For the stork's reaction, what according to you will be a good feedback? I was thinking along the lines of stork's glow vs fade. What do you expect the stork to behave like when hitting an orb or dark?

I think the glow and fade are also nice since they will show a reaction that there is a hit on the orb. I will look around for a perfect sound effect, and let you know when I find one.

>Stages: What is your opinion on an infinite game where the game keeps on speeding up vs a game divided into stages? Which would be more entertaining and engaging according to you?


I prefer speeding up as the level changes. I love the current work done on the landing page, it looks good. Keep up the work buddy.

**Comment by sanjeev309** [comment]
Here is another update on the ongoing work:

- Bird now has flapping audio which increases in pitch when the player commands the bird to fly up. This makes it sound like the bird is actually doing some hard work which sounds aesthetically good!

- Orb and Dark give a sound effect when collected giving feedback to the user. 

- I have figured out the pause feature, implementation part is pending. 

Also, this update will mention you as a contributor on google play store update changes as well as on the contributors list here on Github as @darewealth. Do provide an update on that mention beforehand if you want it otherwise :) 

Stay Tuned! Peace Out!

**Comment by darewealth** [comment]
Wow! I am glad to hear about those updates. I will be expecting the full build for a possible update on the play store, and having my name as one of the contributors would be a great pleasure. :) Thank you

**Comment by sanjeev309** [comment]
Commit f56784bbbb07b98938588db8124775efe0934f17 implements most of the suggestions presented. Further refinements are planned and will be implemented soon. This issue is now being closed, feel free to reopen if required or raise a new one. Thank you for your contribution :smile:
