### ISSUE TITLE
Bug: Bird disappeared when game is re-launched

### ISSUE THREAD

**Issue by darewealth** [sanjeev309/storklight#2]
Expected behavior
While the game is still on, I expected that when I press on the mobile minimize button, it should minimize, and when I want to continue the game should continue since it was minimized.

Actual behavior
When I clicked on the minimize button, the game minimized, but when I re-enter the game, The bird was not on the screen again, the screen was just sliding by itself.

How to reproduce
Launch the game
Click on mobile minimize button
Go back to the game

App version:

Operating system: Android 6.1

Device: Itel

Recording Of The Bug
https://youtu.be/7oLVPy_cMQE

**Comment by sanjeev309** [comment]
Hi @darewealth , Thank you for the bug report! The bug is reproducible. Will fix and comment the commit which fixes it. 

Feel free to open new issues if you have more suggestions/ bug reports/ feature requests :+1:

**Comment by sanjeev309** [comment]
Commit b102c05 automatically resolves this issue by implementing pause feature.
