### ISSUE TITLE
Suggestions For StorkLight :  Add the "DIFFICULTY  SETTING" and "SENSITIVITY" features

### ISSUE THREAD

**Issue by ahyar92** [sanjeev309/storklight#3]
![2.png](https://cdn.steemitimages.com/DQmfCHkXRs1gyRsLa9b69oJmGFFDCV4BQydfZBe7ouYczwH/2.png)

![1.png](https://cdn.steemitimages.com/DQmcEJP53kVUwTttYgkj39NRvnet4S6s1QVcuqvShYAky38/1.png)

### Components
The components (Features) I want to suggest is:
<table>
<thead>
<tr><th>Feature Name</th><th>Points</th>
</thead>
<tbody>
<tr><td> DIFFICULTY  SETTING</td><td>EASY, NORMAL and HARD</td>
<tr><td> SENSITIVITY</td><td>OVERALL and FLYING SENSITIVITY</td>
</table>

![1.png](https://cdn.steemitimages.com/DQmcEJP53kVUwTttYgkj39NRvnet4S6s1QVcuqvShYAky38/1.png)

### Proposal Description
[StorkLight](https://github.com/sanjeev309/storklight) is a very interesting game. I like the concept presented by StorkLight, because I often played similar games like StorkLight. What impressed me the first time was the graphics of this game. Storklight looks very classic, I really like the look of the graphics.

Indeed, in terms of features, StorkLight is still very minimal. The user cannot find anything else, because when opening StorkLight the user goes directly to the game. And I think, developers have to make more improvements to StorkLight to make it more attractive.  With the development and addition of several features, this certainly can make StorkLight able to compete with similar applications. Not only that, but it can also increase user experience later.  And also in my opinion, the role of contributors and users is needed by developers to improve the quality of StorkLight later.

And I see, @darewealth has contributed very good suggestions [here](https://github.com/sanjeev309/storklight/issues/1). All suggestions from @darewealth are very useful for StorkLight. And at this time, I also want to suggest some features for StorkLight that can provide a new atmosphere for StorkLight.

#### 1. Difficulty Setting
"Difficulty Setting" is the first feature I want to recommend to StorkLight. And this in my opinion is a very important and interesting feature. The "Difficulty Setting" feature serves to see how far the user is able to play this game.  

This "Difficulty Setting" feature can measure the ability of users to play StorkLight in three stages, namely Easy, Normal and Hard. The concept of the "Difficulty Setting" feature will provide different challenges in the game according to the chosen difficulty level. This feature certainly will not make users bored in playing StorkLight, because it will provide a challenging game sensation. And also with the "Difficulty Setting" feature, this certainly helps users to play games easily on Easy level.

#### 2. Sensitivity (Flying Sensitivity)
This is a possibly rare feature that you won't find in other similar applications. But from the results of my research so far in playing similar games like StorkLight, I think the developer must pay attention to this my suggest. 

With the "Sensitivity" feature that can adjust the sensitivity of flying from birds (Stork), this certainly helps users to be able to adjust the sensitivity of the flight speed of Stork as desired by the user.

#### How the Sensitivity feature works:
The working concept of the "Sensitivity" feature is very simple. The greater the flying sensitivity is set, the faster the flying speed from Stork will be. And vice versa, the smaller the sensitivity set, then the power of flying up from Stork will be slower. 

![1.png](https://cdn.steemitimages.com/DQmcEJP53kVUwTttYgkj39NRvnet4S6s1QVcuqvShYAky38/1.png)

### Mockups / Examples
Below I will show examples of locations or illustrations if the features I recommend are implemented by the Developer.

![3.png](https://cdn.steemitimages.com/DQmaqtiLfmSLkBmJzcqYTNhoDmXijcQ4gqRPbQKFmyYTRBb/3.png)

![4.png](https://cdn.steemitimages.com/DQmU2p1KD3oviqdXVvLiQJX46eV8KjwvHNnJK6GxmmEXhKC/4.png)

---

![5.png](https://cdn.steemitimages.com/DQmbZTSURhse11jzL6umZU3GE7g7d7BhqPjCbFxPcwfWABj/5.png)

![6.png](https://cdn.steemitimages.com/DQmR4sxYFqFUmDVfuSvcgTG94d3t5Y6L6VRpndMSgUA2uom/6.png)

![1.png](https://cdn.steemitimages.com/DQmcEJP53kVUwTttYgkj39NRvnet4S6s1QVcuqvShYAky38/1.png)

### Benefits

The benefits of the features above are as follows:
#### 1. Difficulty Setting
With the "Difficulty Setting" feature, users can practice the ability to play StorkLight games on three levels, namely Easy, Normal and Hard. And also, the "Difficulty Setting" feature will provide an interesting stage of the game. Because users can try game difficulties based on their abilities and desires.

#### 2. Sensitivity (Flying Sensitivity)
With the "Sensitivity (Flying Sensitivity)" feature, users can adjust the flying sensitivity of Stork according to what the user wants. 

StorkLight users certainly have different levels of reflex. Some of them have fast reflexes, but also the opposite. Because this game requires good reflexes, the "Sensitivity (Flying Sensitivity) feature" is needed to regulate the flying power of storks according to their comfort.

![1.png](https://cdn.steemitimages.com/DQmcEJP53kVUwTttYgkj39NRvnet4S6s1QVcuqvShYAky38/1.png)

### Conclusion
To implement the features above, developers may need to make improvements to StorkLight. For the "Difficulty Setting" feature I think it's not too difficult how to apply the working concept, because this is a very common feature available in game applications. As for the "Sensitivity (Flying Sensitivity) feature" the developer might need time to learn the concept of work because this feature is rarely available in other similar applications.

I think, it won't matter if the developer has to work hard for it. Because it will have a good effect for StorkLight and users. If StorkLight can improve user experience, this can certainly add value to StorkLight and its developers.

And I hope, developers can immediately implement my suggestion.

Thank You :)

**Comment by sanjeev309** [comment]
Hi @ahyar92 , Thank you for taking out time for such a detailed suggestion! 

For the difficulty setting, StorkLight will be made as an infinite side-scroller where the difficulty keeps on increasing. This will make the game challenging as well as engaging.

As for sensitivity, It is possible to include this as a configuration. So I will be scheduling this in the next to next update as the next update includes most of [@darewealth](https://github.com/darewealth)'s suggestions :smile: 

Also, Your mockups are amazing! Mind if I adopt a similar style for in game menu? Those look very clean and amazing! :smile: 

Thank you for your valuable contribution : )

**Comment by ahyar92** [comment]
Of course it doesn't matter if you adopt a menu style from me. Even I am very happy :). And thank you for your attention :)

And thank you for accepting my suggestion :)

**Comment by sanjeev309** [comment]
Commit f56784bbbb07b98938588db8124775efe0934f17 implements increasing difficulty with score. This issue is resolved. Please feel free to reopen if required.
