### ISSUE TITLE
Ability To Suggestion (Game controller Touch   )Feature in StorkLight - Open Source Side Scroller (Unreleased)

### ISSUE THREAD

**Issue by nasirshah1813** [sanjeev309/storklight#4]
# Repository
https://github.com/sanjeev309/storklight

# Introduction

[StorkLight ](https://play.google.com/store/apps/details?id=com.studio.sanjeev.storklight)- Open Source Side Scroller (Unreleased) android game. this gives you the challenge to fly stork as long as.
this is a very simple game I really enjoyed this game.

# Components
The components (Features) I want to suggest is

1- Game controller Touch  

# Proposal Description

According to my information, this is a very easy and simple game but I like to suggest some feature in the application this feature give more benefits. 

#### Game controller Touch  

Game controller Touch is the simple feature to control the stroke easy with the help of this feature you can control your Game bird easy and fast with the help of your finger you can play the game. the  StorkLight - Open Source Side Scroller (Unreleased) will be more easy for users. 

With this button/option  you can move your Stork up, down,  and Around, on the secreen.

# Mockups / Examples
![1.png](https://ipfs.busy.org/ipfs/Qmf4pGU3PpoKooqzmJynLAjWEjXeRTN5nSqhaRmc4euoot)

![2.png](https://ipfs.busy.org/ipfs/QmZBkkxkE1PCvWZndtzPGsa1QaB7GXwJfd3f9xcF7HX6xa)

# Benefits

I think with the help of this feature Controlled the bird/stroke easy and fast. The game will be more beneficial for users. With the help of this feature, users will play the game long time.   

# GitHub Account
https://github.com/nasirshah1813

**Comment by sanjeev309** [comment]
Hi @nasirshah1813, Thank you for taking out time for the suggestion. 

For the joystick implementation, I personally see the game to be user friendly and simplistic with as less controls as possible. A joystick might annoy a lot of users whereas tapping anywhere appears intuitive and leaves the decision to the user.

I personally play with my left hand whereas I have observed that others play using different areas of the screen. I lieu of that, I cannot ensure that the joystick feature will be worked upon until we get multiple requests for this feature in the future. 

Feel free to give further feedback by creating a new issue, Thank you for your help making StorkLight better : )
